### ISSUE TITLE
Error while executing DDQN for defend_the_center.cfg

### ISSUE THREAD

**Issue by yculcarnee** [flyyufelix/VizDoom-Keras-RL#6]
Following error was raised when executing ddqn.py 

```
Traceback (most recent call last):
  File "VizDoom-Keras-RL/ddqn.py", line 309, in <module>
    r_t = agent.shape_reward(r_t, misc, prev_misc, t)
  File "VizDoom-Keras-RL/ddqn.py", line 112, in shape_reward
    if (misc[2] < prev_misc[2]): # Loss HEALTH
IndexError: index 2 is out of bounds for axis 0 with size 2
```

Any reasons why?

**Comment by AloshkaD** [comment]
Same error here, have you fixed it @yculcarnee ?

**Comment by AloshkaD** [comment]
The problem is that the passed list has two elements only. commenting out that line should work for now.

**Comment by yangxin-1124** [comment]
> The problem is that the passed list has two elements only. commenting out that line should work for now.

May I ask which line should be commented out?
